#script for inserting and running new script on the output of matrix of simulations generated by matrixtest.sh 
#pyton file needs to be in same directory as this script
module load python/3.5.1

cd test

#array for decrease in fitness k (needs to match matrixtest.sh)
FITNESS=(0 95 100) #decrease to fitness is k

#array for selection p (needs to match matrixtest.sh)
SELECTION=(1 3 1000) #positive selection is p

#creates directories for each 1, 10, 100, 1k loci in one directory titled "test"
#creates directories for each combination of decrease in fitness and selection we want using the arrays 

for i in 1 10 100 1000 #the number of loci
do
   cd $i"loci"
   for k in ${FITNESS[@]}; do
   for p in ${SELECTION[@]}; do
   cd $k"df_"$p"s"
   #insert name of python script that needs to be inserted, replace poptime.py
   cp ../../../poptime.py .
   name=$i"l_"$k"df_"$p"s"
   mem=200
   queue="--partition=general"
   days=7
   id=$(sbatch $dep --ntasks=1 --cpus-per-task=1 -N 1 --job-name=${name}.gen --output=${name}_poptime.out --mem=${mem}00 $queue --time=${days}-0 --wrap="python3 poptime.py -l $i -s $p -d $k")
   echo $id
   cd ..
   done
   done
   cd ..
done
cd 
